### ISSUE TITLE
Every image from stable-diffusion-xl-1024-v1-0 endpoint contains pixel artifacts

### ISSUE THREAD

**Issue by vince-alcivar** [Stability-AI/rest-api-support#44]
I’m using the Stability API to generate images. Every single image I create has these off-color pixels. The pixels are more noticeable in some images than others depending on the colors, but they are always there. I’ve tried every combination of steps, cfg, sampler, and clip guidance. The pixels aren’t very noticeable at normal resolution but if you zoom in you can see them cleary. The pixels remain even after upscaling, and they are even more noticeable.

Is this supposed to be the “invisible” watermark? Is there some setting to reduce the appearance of these pixels that I’m missing?

I notice other models like DallE3 don’t have these pixels. I also notice images from other older SD models like stable-diffusion-512-v2-1 don’t appear to contain these pixels. 

See image for example:
![82BC49DA-FF8E-4893-A2CE-695C6DE655D6](https://github.com/Stability-AI/rest-api-support/assets/51487391/3370f472-977d-46f0-a09c-710aa2654825)

**Comment by vince-alcivar** [comment]
Adding a couple more examples. I want to upscale these images to print them but these pixels look awful even in the upscaled images. Any help would be appreciated.

![F89A2D88-A31B-4B1F-886E-D0E9A4297215](https://github.com/Stability-AI/rest-api-support/assets/51487391/7471fb02-1dd6-49e9-9a8e-5800344e59fd)
![DCA46A84-DD96-4E46-9CC2-2024D0D92ACC](https://github.com/Stability-AI/rest-api-support/assets/51487391/7c6f0942-1f66-4426-bbe2-abe8168705f8)

**Comment by vince-alcivar** [comment]
Bumping this. Any guidance would be great.

**Comment by enzymezoo-code** [comment]
Yes, those pixels are likely caused by the watermark. 

Here is a script to detect it:
[https://github.com/Stability-AI/generative-models/blob/main/scripts/demo/detect.py](https://github.com/Stability-AI/generative-models/blob/main/scripts/demo/detect.py)

The watermark seems to be more visible on parts of images that have flat color and not much texture. Thank you for the valuable feedback. We'll take this into account as we improve the API.

**Comment by vince-alcivar** [comment]
@enzymezoo-code  got it, thanks for taking a look.

I have one more question if you don’t mind. I tried emailing platform@stability.ai a couple times but haven’t gotten a response. I basically want to know if commercial usage of the api is allowed, as in building a website that calls the api in the backend. I see there is a commercial membership plan for self hosted models but no mention of the api.

**Comment by enzymezoo-code** [comment]
From the [FAQ](https://stability.ai/faq):

> How does the Stability AI membership relate to other Stability AI products and services, such as the Stable Image API or Stable Audio?
> The Stability AI memberships are specifically designed to give our members commercial rights for self-hosting our Core Models in your Virtual Private Cloud (VPC), locally on-premise, or on your edge devices. It does not apply to usage of our cloud-hosted services or products, which are powered by the Core Models but which are run on the cloud infrastructure of Stability AI.

**Comment by vince-alcivar** [comment]
Thanks for the quick response! Right, my understanding is the memberships do not apply to the api. So my question is, can I use the api for commercial purposes (i.e. to build a website)? Or is it only meant for me, as a single end user?

**Comment by enzymezoo-code** [comment]
Right, you can use [our Stability API](https://platform.stability.ai/) commercially without a membership. 👍

**Comment by vince-alcivar** [comment]
Perfect thank you!
